FEATURE_AI_INSIGHTS = "ai_insights"
FEATURE_MAX_AI_QUERIES_PER_MONTH = "max_ai_queries_per_month"
FEATURE_CHAT_SUPPORT = "chat_support"
FEATURE_MAX_CHAT_CONVERSATIONS_PER_MONTH = "max_chat_conversations_per_month"
FEATURE_MAX_FACILITIES = "max_facilities"
FEATURE_MAX_MEMBERS = "max_members"

PROVIDER_MANUAL = "manual"
PROVIDER_STRIPE = "stripe"

SUBSCRIPTION_STATUS_ACTIVE = "active"
SUBSCRIPTION_STATUS_CANCELED = "canceled"
SUBSCRIPTION_STATUS_PAST_DUE = "past_due"
SUBSCRIPTION_STATUS_PAUSED = "paused"
SUBSCRIPTION_STATUS_TRIALING = "trialing"

DEFAULT_FREE_PLAN_CODE = "free"
