# Generated by Codex on 2026-03-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityfacility",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facilities",
                to="accounts.institution",
            ),
        ),
    ]
