# Generated by Codex on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_securityfacility_institution"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.CharField(max_length=64, unique=True)),
                ("trigger_status", models.PositiveSmallIntegerField()),
                ("hit_count", models.PositiveIntegerField(default=0)),
                ("last_path", models.CharField(blank=True, max_length=255)),
                ("reason", models.CharField(max_length=255)),
                ("blocked_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-blocked_at"],
            },
        ),
    ]
