# Generated by Django 4.2.27 on 2026-01-14 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ob_number', models.CharField(max_length=50)),
                ('incident_type', models.CharField(choices=[('robbery', 'Robbery'), ('assault', 'Assault'), ('accident', 'Accident'), ('missing_person', 'Missing Person'), ('murder', 'Murder'), ('theft', 'Theft'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('occurred_at', models.DateTimeField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securityfacility')),
            ],
        ),
    ]
